name: Default Issue
description: Raise an issue that wouldn't be covered by the other templates.
title: "Issue: <Please write a comprehensive title after the 'Issue: ' prefix>"
labels: [Default Issue Template]

body:
  - type: textarea
    attributes:
      label: "Issue you'd like to raise."
      description: >
        Please describe the issue you'd like to raise as clearly as possible.
        Make sure to include any relevant links or references.

  - type: textarea
    attributes:
      label: "Suggestion:"
      description: >
        Please outline a suggestion to improve the issue here.
